version: '3.8'

services:
  src-cloud:
    build: .
    image: starrail-copilot-cloud:latest
    container_name: src-cloud-web
    restart: unless-stopped
    ports:
      - "22367:22367"
    volumes:
      - ./config:/app/config
      - ./log:/app/log
    environment:
      - TZ=Asia/Shanghai